version: '3.9'
services:
  mysql:
    container_name: mysql-8v3
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Complex!PW@3306